# Generated by Django 3.0.3 on 2020-04-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyo', '0002_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='gender',
        ),
    ]
