# Generated by Django 3.0.3 on 2020-04-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyo', '0005_flights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carss',
            name='hours',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='carss',
            name='mins',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='carss',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
