# Generated by Django 3.0.3 on 2020-05-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyo', '0006_auto_20200430_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_quota', models.CharField(max_length=30)),
                ('train_name', models.CharField(max_length=30)),
                ('choice_two', models.CharField(max_length=40)),
                ('From', models.CharField(max_length=30)),
                ('to', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
