# Generated by Django 3.0.3 on 2020-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyo', '0008_nxt1'),
    ]

    operations = [
        migrations.CreateModel(
            name='nxt2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('alternative_mobile', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('account_holdername', models.CharField(max_length=30)),
                ('account_number', models.IntegerField()),
                ('branch_name', models.CharField(max_length=30)),
                ('wallet', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
