# Generated by Django 3.0.3 on 2020-05-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyo', '0009_nxt2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nxt2',
            name='account_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='nxt2',
            name='alternative_mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='nxt2',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='nxt2',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
