# Generated by Django 3.0.3 on 2020-05-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyo', '0010_auto_20200504_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Picture', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
