# Generated by Django 3.0.3 on 2020-05-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyo', '0011_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='waterparks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_destination', models.CharField(max_length=30)),
                ('Picture', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
