# Generated by Django 3.0.3 on 2020-05-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyo', '0014_hotelsss'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('stay', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=40)),
                ('plan', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=12)),
                ('desc1', models.CharField(max_length=30)),
                ('plan2', models.CharField(max_length=20)),
                ('photo2', models.CharField(max_length=10)),
                ('desc2', models.CharField(max_length=10)),
                ('btn', models.CharField(max_length=10)),
                ('btn1', models.CharField(max_length=10)),
                ('btn2', models.CharField(max_length=10)),
                ('btn3', models.CharField(max_length=10)),
                ('btn4', models.CharField(max_length=10)),
                ('photo3', models.CharField(max_length=10)),
                ('photo4', models.CharField(max_length=10)),
                ('hotelname', models.CharField(max_length=10)),
                ('pla', models.CharField(max_length=10)),
                ('hotelplan', models.CharField(max_length=10)),
                ('hdes', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
