# Generated by Django 3.0.3 on 2020-05-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyo', '0015_viewdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewdetail',
            name='photo',
            field=models.ImageField(max_length=12, upload_to=''),
        ),
        migrations.AlterField(
            model_name='viewdetail',
            name='photo2',
            field=models.ImageField(max_length=10, upload_to=''),
        ),
        migrations.AlterField(
            model_name='viewdetail',
            name='photo3',
            field=models.ImageField(max_length=10, upload_to=''),
        ),
        migrations.AlterField(
            model_name='viewdetail',
            name='photo4',
            field=models.ImageField(max_length=10, upload_to=''),
        ),
    ]
