# Generated by Django 3.0.3 on 2020-04-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('album', models.CharField(max_length=20)),
                ('extra', models.CharField(max_length=20)),
                ('offer', models.BooleanField(default=False)),
                ('cont', models.ImageField(upload_to='pics')),
                ('videofile', models.FileField(null=True, upload_to='videos', verbose_name='files_name')),
            ],
        ),
    ]
