# Generated by Django 3.0.3 on 2020-04-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos', verbose_name='videofile'),
        ),
    ]
